# Add configuration values here, as shown below.
#

twitter_key: 8J4OK1Ngpyj3mzFKI1BGvpNmN
twitter_secret:	v5SngVhkEc46cOTSgzIiLCrE4wsFO3SvuA3cKyCPi73ELyWZAK

#
# production:
#   stripe_api_key: sk_live_EeHnL644i6zo4Iyq4v1KdV9H
#   stripe_publishable_key: pk_live_9lcthxpSIHbGwmdO941O1XVU
